#!/usr/bin/env bash
# Function to display subdomain information

# www --> 184935-lb-01 54.197.87.216
# web-01 --> 184935-web-01 52.3.250.203
# web-02 --> 184935-web-02 54.89.194.149

display_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type

    if [[ -z "$subdomain" ]]; then
        # Display information for default subdomains
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        # Display information for the specified subdomain
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        record_type=$(dig +short "$sub.$domain" | awk '{print $4}')

        if [[ -n "$record_type" ]]; then
            destination=$(dig +short "$sub.$domain" | awk '{print $1}')
            echo "The subdomain $sub is a $record_type record and points to $destination"
        else
            echo "The subdomain $sub does not exist"
        fi
    done
}

# Check if domain and subdomain parameters are provided
if [[ $# -eq 2 ]]; then
    domain="$1"
    subdomain="$2"
    display_info "$domain" "$subdomain"
elif [[ $# -eq 1 ]]; then
    domain="$1"
    display_info "$domain"
else
    echo "Invalid number of arguments. Usage: script.sh domain [subdomain]"
fi
