#!/usr/bin/env bash
# Installs, configures, and starts the load balancer
#!/usr/bin/env bash

# Update package repositories
sudo apt-get update

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAProxy
CONFIG_FILE="/etc/haproxy/haproxy.cfg"
BACKEND_SERVERS="184935-web-01 184935-web-02"

# Create a backup of the default HAProxy configuration file
sudo cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"

# Generate the new HAProxy configuration
cat <<EOF | sudo tee "$CONFIG_FILE" > /dev/null
frontend http-in
    bind *:80
    mode http
    default_backend servers

backend servers
    balance roundrobin
    server 184935-web-01 52.3.250.203:80 check
    server 184935-web-02 54.89.194.149:80 check
EOF

# Restart HAProxy service
sudo service haproxy restart
