#!/usr/bin/env bash

cp /etc/hosts ~/hosts.new

# Add localhost entry to ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new

# Add facebook.com entry to ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts
